<div class="card border-0 shadow-lg">
    <div class="card-body p-0">
        <div class="row">

            <div class="col-md-12 d-md-block animate__animated animate__fadeIn">
                <div class="col-md-8 mx-auto">
                    <div class="my-3">
                        <div class="my-3">
                            <div class="mx-auto text-center">
                                <img src="img/logoPsicologia_3D_2.jpg" class="img-fluid" alt="logo"
                                    style="width: 350px;">
                            </div>
                            <h1 class="text-center h2">
                                Área de Atención Psicológica
                            </h1>
                            <br>
                            <p class="text-justify">
                                1. Es un requisito obligatorio que todos (a) los (a) pacientes que
                                solicitan el servicio de atención psicológica por
                                primera vez tomen la plática de inducción, donde se
                                brinda información importante sobre sus orientaciones
                                psicológicas, así como los lineamientos y reglamento
                                del uso del servicio. Esta plática se imparte todos los
                                días lunes a las 11: 00 am y a las 4:00 pm.
                                <br />
                                <br />
                                2. Los paciente de primera vez, deberán registrarse en
                                la plataforma con los siguientes datos, para crear una
                                cuenta en la plataforma, y de esta manera estar
                                gestionando sus citas de seguimiento con su terapeuta
                                asignado.
                            </p>
                            <br />
                            <div class="row justify-content-center">
                                <div class="col-md-6 my-3">
                                    <a href="menu.aspx?id=registro" class="btn btn-secondary btn-lg btn-block">
                                        <span class="icon">
                                            <i class="fas fa-flag"></i> Regístrate
                                        </span>
                                    </a>
                                </div>
                                <div class="col-md-6 my-3">
                                    <a href="#" class="btn btn-success btn-lg btn-block">
                                        <span class="icon">
                                            <i class="fas fa-check"></i> Iniciar sesión
                                        </span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>