<div class="card border-0 shadow-lg">
    <div class="card-body p-0">
        <div class="row">

            <div class="col-md-12 d-md-block animate__animated animate__fadeIn">
                <div class="col-md-8 mx-auto">
                    <div class="my-3">
                        <div class="my-3">
                            <div class="mx-auto text-center">
                                <img src="img/registro_2.jpg" class="img-fluid" style="width: 350px;">
                            </div>
                            <h1 class="text-center h2">
                                Regístrate
                            </h1>
                            <br>
                            <p class="text-justify">
                                Los y las pacientes de primera vez, deberán registrarse en
                                la plataforma con los siguientes datos, para crear una
                                cuenta en la plataforma, y de esta manera estar
                                gestionando sus citas de seguimiento con su terapeuta
                                asignado.
                            </p>
                            <br />
                            <div class="row text-center mx-auto">
                                <a href="menu.aspx?id=estudiantes" class="col-md-6 my-3 text-center">
                                    <img src="img/estudiante.jpg" class="img-fluid" style="width: 150px;">
                                    <p class="h6">Registro Estudiante</p>
                                </a>
                                <a href="menu.aspx?id=docentes" class="col-md-6 my-3 text-center">
                                    <img src="img/docente.jpg" class="img-fluid" style="width: 150px;">
                                    <p class="h6">Registro Docente</p>
                                </a>
                            </div>
                            <br>
                            <div class="row justify-content-center">
                                <div class="col-md-12 my-3">
                                    <a href="menu.aspx?id=home" class="btn btn-secondary btn-lg btn-block">
                                        <span class="icon">
                                            <i class="fas fas fa-arrow-left"></i> Regresar
                                        </span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>